#!/usr/bin/env bash
#script that displays information about subdomains
#it should have domain and subdomain as the argument 

all_subdomains=("www" "lb-01" "web-01" "web-02")

runDig () {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" |grep -A1 'ANSWER SECTION' | tail -1 | awk -v s="$subdomain" 'BEGIN {fs = " "} ; { print "The subdomain " s " is a " $4 " record and points to " $5 "}'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${all_subdomains[@]}"
    do
        rundig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then  
    domain="$1"
    subdomain="$2"
    runDig "$subdomain" "domain"
fi
