#!/usr/bin/env bash
#scrpt that transdfers program from client to server.

num=3
if [ "$#" -lt "$num" ];then 
    echo 'usage: 0-transfer_file PATH_TO_FILE IP USER PATH_TO_SSh_KEY'
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"2":~/
fi 
