#!/usr/bin/env bash
#define the custom header and value
header_name="x-Served-By"
header_value="$(hostname)" 

#install nginx if not installed

if ! command -v nginx &> /dev/null
then
    sudo apt-get -y update
    sudo apt-get -y install nginx
fi

#create a hello world page
echo "Hello World!" |sudo tee /var/www/html/index.html

#redirection for the website
sudo sed -i '/server_name _;/a \    return 301 https://www.youtube.com/watch?v=QH2-TGU1wu4;\n    }' etc/nginx/site-available/default
#add custom HTTP header file to the nginx config file
sudo sed -i "http {/a \    add_header $header_name $header_value;" /etc/nginx/nginx.config

#add a custom 404 page
echo "ceci n'est pas une page" | sudo tee /var/www/html/custom_error.html

#configure nginx to use the 404 pag
sudo sed -i "/server {/a \    error_page 404/custom_404.html;" /etc/nginx/sites-available/default
#restart nginx 
sudo systemctl restart nginx
