#!/usr/bin/env bash
#A script that pings an ip address pssed as an argument

IP="${1}"
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
    echo "Usage: ${fn} {IP_ADDRESS}"
else
    ping -c 5 "${IP}"
fi
