#!/usr/bin/env bash
#Identify what keeps ubuntu container's nginx from listening from port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-available/default
service nginx restart
