#!/usr/bin/env bash
#displays Best School 9 times then prints Hi after the 9th time

i=0
while (("$i" < 10));
do
    if [ "$i" == 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
        ((i++))
done
