#!/usr/bin/env bash
#bash script that outputs hours and minutes

hrs=0
while [ "$hrs" -le 13 ];do
    mins=1
    while [ $mins -lt 60 ];do
        echo "$mins"
        ((mins++))
    done
    ((hrs++))
done
