#!/usr/bin/env bash
#script that configures a file to run nginx as nginx, listening on all active ports on port 8080 

#stop nginx and kill apache
sudo service stop nginx
sudo pkill apache2

#change to nginx user
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

#append the nginx to listen to all active ports on port 8080
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-availab;le/default

#check config files for syntax error 
sudo nginx -t

#restart nginx
sudo service restart nginx
